// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/farwydi/vtbb-demo/pkg/graphql"
)

// Injectors from wire.go:

func setup(config AppConfig) (application, func(), error) {
	resolver := graphql.NewResolver()
	handler := graphql.NewRouter(resolver)
	mainApplication := newApplication(handler)
	return mainApplication, func() {
	}, nil
}
